### PR TITLE
Added several python packages my courses need.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
@celine168

**Comment by celine168** [comment]
Building the Dockerfile now.

**Comment by moorepants** [comment]
Celine, I was just thinking that you could probably setup a CI service to build these docker images for testing purposes. It would relieve you from having to do it manually. Next time we meet you can explain what you do and we can figure out if setting up CI is a good option.

**Comment by celine168** [comment]
Yes I'm looking into using Travis CI for these files.

All of these packages should be added to the Default Environment now. I haven't had the chance to test each of them individually yet though.

**Comment by celine168** [comment]
Reopened to merge.

**Comment by moorepants** [comment]
I'm confused why you are merging. How do you know this is the same as the dockerfile you actually built?

**Pull request merged**
