### PR TITLE
Add packages requested by Sarah Stewart (GEL298)

### PR DESCRIPTION
**Pull request by celine168**
[WIP] Submitting PR to build on Docker Cloud. I'm also building locally to since I have layers cached so hopefully it will take a bit faster.

### CODE REVIEW

**Comment by celine168** [comment]
Just a quick update: the layers on my sealion server are cached, so the file did build successfully even though the one on DockerHub didn't. DockerHub builds Dockerfiles from scratch without any caching, which will cause the check to fail.
PR #33 should fix that problem once it's merged. 
I'm updating the staging jhub right now so we could test new image sometime.

**Comment by moorepants** [comment]
Thanks Celine!

Don't let this take up too much of your time today if you need to do school work.

**Comment by celine168** [comment]
No worries, I'm multi-tasking.
The image is now live on staging, feel free to play around. 
Cartopy/other packages seem to work just fine. The matplotlib extension doesn't currently work though so I'm going to try another image with the `ipympl` version pinned.
Just to be sure: we won't be installing `pygmt` in our Dockerfile because it's cloned from a GitHub repo, correct?

**Comment by moorepants** [comment]
>  Just to be sure: we won't be installing pygmt in our Dockerfile because it's cloned from a GitHub repo, correct?

Correct. I want to stick to installing from conda (and pip if we really have to). No installs of non-"official" releases that are packaged up and guaranteed to work.

**Comment by moorepants** [comment]
It does look like pygmt has an alpha release on pypi: https://pypi.org/project/pygmt/. I guess we could pip install it along with pyshtools, but installing alpha stuff isn't really a good idea. Let's not install any form of pygmt. The students can install it themselves.

**Comment by celine168** [comment]
The new Docker image is live on Staging right now. I've tested it out and it seems good to go to me. 
I can push up the image manually up to DockerHub and change Default Environment image once I have the okay.
Note: it will still probably fail on the Docker Cloud build due to uncached layers, so I plan on manually pushing the current image up.

**Comment by moorepants** [comment]
Sounds good. Go for it! Thanks.

**Comment by celine168** [comment]
Cool, I'll wait until later tonight to upgrade. (hopefully there will be fewer users)

**Comment by celine168** [comment]
The image is now live on JupyterHub. However, users must restart their servers in order for pyshtools to take effect after cloning and installing pygmt.

**Comment by moorepants** [comment]
@celine168 I'd like to be able to see these dockercloud builds. When I click details I get a 404. Do I need an account and you add me or something? Maybe I can help get it running.

**Comment by celine168** [comment]
I've been building them locally on the sealion server (details to access are in the metalc-configurations).
The current master branch does not successfully build on DockerHub, though if you do want to see them, you can go to hub.docker.com and log in (details are also in metalc-configurations).

**Comment by moorepants** [comment]
I logged into dockerhub but it still gives me a 404. I can try to get things working on dockerhub.

**Comment by celine168** [comment]
https://hub.docker.com/repository/registry-1.docker.io/libretexts/default-env/timeline lists the builds, by commit.
DockerHub just takes the pushes from GitHub and builds them (or I manually push them up there which is what I've been doing). There are only build logs. The failed tests should be fixed by #33, since we explicitly pin the versions.
I'm going to try pinning gmt to 6.0.0 locally one last time. There have been weird conda errors when I try to pin it. If you could please wait for ~another hour so I can build the image.

**Comment by celine168** [comment]
I have another environment on the staging jhub with gmt=6.0.0
I can't exactly tell if the cartopy tutorial works from scratch since I've already setup pygmt (which seems to be persistent for some reason). All the other kernels seem to work just fine.

**Pull request closed without merging**
