### PR TITLE
Install server-proxy for RStudio button

### LINKED ISSUE #128: Add button to JupyterLab interface to open RStudio server

### PR DESCRIPTION
**Pull request by celine168**
Closes https://github.com/LibreTexts/metalc/issues/128

### CODE REVIEW

**Comment by celine168** [comment]
It's live on JupyterHub now and there's a nice R-Studio button on the Launcher. Doesn't seem to conflict with anything else.

**Comment by moorepants** [comment]
Works for me! Very nice.

**Comment by moorepants** [comment]
Not sure if you have control over this, but I think the button should be in the "Other" section not the "Notebook" section, as it isn't a notebook interface.

**Comment by celine168** [comment]
Looks someone very recently opened an issue about this (18 hours ago, what good timing)! https://github.com/jupyterhub/jupyter-rsession-proxy/issues/87

**Comment by celine168** [comment]
Someone also mentioned that if the icon is located in the Other section, it is harder to access. Just something to consider.

**Pull request merged**
