### PR TITLE
Add biocmanager

### PR DESCRIPTION
**Pull request by celine168**
Upon Richard's request.

### CODE REVIEW

**Comment by moorepants** [comment]
@celine168 Is this needed still? If not, it can be closed.

**Comment by celine168** [comment]
Hmm...this request was made by Richard. I can ping him in the morning about this (I don't want to wake him up right now).

**Comment by moorepants** [comment]
It wouldn't hurt anything to add it likely. If you want to adjust the pr to modify the new files with this package, that's fine.

**Comment by celine168** [comment]
Biocmanager seems to be succesfully installed:
image

And it's currently the image on staging (default-test:bioc).

**Comment by rkevin-arch** [comment]
Closing in favor of 8f16f3c81cd1ae49137d24e2090f0904ab025c24

**Pull request closed without merging**
